### ISSUE TITLE
Deploy the repo to Netlify

### ISSUE THREAD

**Issue by aravindesri** [aravindesri/arcgis-storymaps-gallery#3]
#### Tasks
- [ ] Create a netlify.toml file with build parameters
- [ ] Merge changes to the Master
- [ ] Setup Netlify site
- [ ] Change sitename to `sm-gallery.netlify.com`
